# Generated by Django 6.0.2 on 2026-03-08 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_type', models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('JavaScript', 'JavaScript')], default='Django', max_length=50)),
            ],
        ),
    ]
